services:
  nginx:
    build: /home/houssam/Desktop/1337-projects/Inception/srcs/requirements/nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /home/houssam/data:/etc/nginx/conf.d
    restart: always

