services:
  mariadb:
    build: ./requirements/mariadb
    container_name: inception_mariadb
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/home/houssam/data
    networks:
      - inception_network
    restart: unless-stopped
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: hounejja
      WORDPRESS_DB_PASSWORD: coffee
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress_data:/home/houssam/data/www/html
    restart: unless-stopped

volumes:
  mariadb_data:
  wordpress_data:

networks:
   inception_network:
     driver: bridge
